from machine import Pin 
import time 
led1= Pin(1,Pin.OUT)
led2= Pin(2,Pin.OUT)
led3= Pin(3,Pin.OUT)
led4= Pin(4,Pin.OUT)
led5= Pin(5,Pin.OUT)
led6= Pin(6,Pin.OUT)
led7= Pin(7,Pin.OUT)
led8= Pin(8,Pin.OUT)
while True :
    led1.value(1)
    led3.value(1)
    led5.value(1)
    led7.value(1)
    time.sleep(0.25)
    led1.value(0)
    led3.value(0)
    led5.value(0)
    led7.value(0)
   
    led2.value(1)
    led4.value(1)
    led6.value(1)
    led8.value(1)
    time.sleep(0.25)
    led2.value(0)
    led4.value(0)
    led6.value(0)
    led8.value(0)
    time.sleep(0.5)
